### ISSUE TITLE
Commentaire sur l'image docker

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-cxx-class-boundary-scan#5]
- Il faudrait un volume pour récupérer les logs de la plateforme dans un fichier.

- Tous les fichiers BSDL de ton exemple sont utiles?

- pourquoi tu as fait un volume vers le builder?

**Comment by XdoctorwhoZ** [comment]
- ../../.:/home/builder/panduza-cxx-class-boundary-scan

Cette ligne est bizarre, je ne l'a comprends pas. Les éléments du plugin devraient déjà être intégré à l'image

**Comment by XdoctorwhoZ** [comment]
- ../../../panduza-cxx-platform:/panduza-cxx-platform

Pareil cette ligne je ne comprends pas. Imagines si quelqu'un d'autre doit utiliser ton image il doit faire un volume avec le repo c'est moche.

**Comment by Valossy** [comment]
J'ai retiré tout les volumes qui liais entre la platform et le plugin, et a la place j'ai repris l'image docker en y ajoutant seulement les volumes nécessaires : logs, BoundaryScan et tree
