### ISSUE TITLE
Relecture de code

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-cxx-class-boundary-scan#7]
C'est étrange cet include ??

**#include "/panduza-cxx-platform/src/meta_driver.hxx"**

pourquoi tu commences ton include par '/' tu supposes que panduza-cxx-platform est installé à la racine ?

**Comment by Valossy** [comment]
Headers déplacé vers un dossier spécifique et les chemins d'accès ont été modifié pour pointer vers les header locaux
