### ISSUE TITLE
Ca marche pas chez moi 💥

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-cxx-class-boundary-scan#9]
Salut,

J'ai mis en place les trucs chez moi comme décrit ici:
https://github.com/XdoctorwhoZ/CJMCU-232H-boundary-scan

J'ai aussi sorti les logs
[BoundaryScan.log](https://github.com/Panduza/panduza-cxx-class-boundary-scan/files/9649184/BoundaryScan.log)
[Platform.log](https://github.com/Panduza/panduza-cxx-class-boundary-scan/files/9649185/Platform.log)

Tu peux me dire si c'est un problème de config ou si c'est un problème de sonde ?
Au besoin tu peux améliorer ta version pour avoir de meilleure logs et me demander de relancer une manip

Merci

**Comment by Valossy** [comment]
Samut @XdoctorwhoZ ,

J'ai deux pistes pour ce problème :

Une solution possible est de changer le nom de la probe dans le tree par celle de ta carte, ça peut être une des solutions suivantes :
- "Single RS232-HS"
- "Single A RS232-HSA"
Je ne connais pas exactement comment il a été programmé par rapport au numéro de produit et le numéro de suivi mais de ce que je lis dans les logs, ça doit être une des solutions au dessus.

Si ça ne fonctionne pas, je regarderais demain pour la deuxième piste, je pense que ça peut être aussi un problème de driver vers la probe, je testerai ça demain aussi au cas où sur une vm propre

**Comment by XdoctorwhoZ** [comment]
Merci pour la réponse rapide
J'ai tenter avec les 2 noms que tu proposes, même résultat 😢 
C'est peut être un problème HW, au pire je te ramènerai ma sonde lundi

**Comment by Valossy** [comment]
J'ai réussi a dupliqué ton erreur, et ça a bien l'air d'être un problème de nom de probe lors du chargement. Il faudrait que je créé une erreur quand la probe n'est pas trouvée. 

Tu pourrais me renvoyer les logs que tu as eu avec les deux noms de que t'ai envoyé ? Peut-être qu'il a réussi a trouver la probe mais qu'il y a eu un autre souci derrière (ce qui a l'air le cas j'ai un souci même avec le bon nom de probe).

Sinon oui, je testerai ça lundi avec ta sonde

**Comment by Valossy** [comment]
@XdoctorwhoZ , normalement le problème est fixé. Tu pourras réessayer quand tu auras le temps ?
Il faudra que tu pull à nouveau l'image de la platform et mettre dans le tree au niveau du "probe_name" : "Single RS232-HS"

Normalement, ça doit fonctionner, j'ai fixé deux commandes sur un des scripts qui était nécessaire.

**Comment by XdoctorwhoZ** [comment]
C'est bon le driver se charge merci!

```bash
panduza-cxx-platform | [        3D8AAB80]       jtag_manager.cxx:187      3| .   Probe: Single RS232-HS
panduza-cxx-platform | [        3D8AAB80]       jtag_manager.cxx:27       1| .   Probe ID is : 0
panduza-cxx-platform | [        3D8AAB80]       jtag_manager.cxx:132      6| .   { Print jtag devices
panduza-cxx-platform | [        3D8AAB80]       jtag_manager.cxx:148    ERR| .   .   No Device Found
panduza-cxx-platform | [main thread     ]             loguru.cxx:524   INFO| .   atexit
```

Maintenant il faut que je revois mais connexion il ne détecte pas ma carte 😄
